services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    volumes:
      - ..:/app
    working_dir: /app
    command: python cli/main.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ..:/app
    working_dir: /app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
